# config/routes.yaml

# Import des routes définies avec des annotations dans les contrôleurs
controllers:
    resource: '../src/Controller/'
    type: annotation

#index:
#    path: /
#    controller: App\Controller\DefaultController::index


